name: pneumothoraxdashboard
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.22.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluro: ^2.0.5
  flutter_adaptive_scaffold: ^0.1.10+2
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  universal_html: ^2.2.4
  file_picker: ^8.0.3
  pdfx: ^2.6.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  firebase_analytics: ^11.0.1
  flutter_local_notifications: ^17.1.2
  pdf: ^3.11.1
  printing: ^5.13.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/appLogo/
    - assets/pdf/
    - assets/svg/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
