// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJwRd2ZQuMn-SE36tOk1gnCs6FPafGsg',
    appId: '1:818251760564:web:9ae4c651794ce95e9728e1',
    messagingSenderId: '818251760564',
    projectId: 'qiot-pneumothorax',
    authDomain: 'qiot-pneumothorax.firebaseapp.com',
    storageBucket: 'qiot-pneumothorax.firebasestorage.app',
    measurementId: 'G-PK0PD0PFMC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRaN5CbL9YKJRRPNJptE3Vc82-X5BsEU',
    appId: '1:818251760564:ios:4329ccdda054597a9728e1',
    messagingSenderId: '818251760564',
    projectId: 'qiot-pneumothorax',
    storageBucket: 'qiot-pneumothorax.firebasestorage.app',
    iosBundleId: 'com.qiot.pneumothoraxdashboard',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBneB4Yzo7dYae0ZPx4iTU6VZjl3y_LVmI',
    appId: '1:818251760564:android:52b0d2a7b39535c89728e1',
    messagingSenderId: '818251760564',
    projectId: 'qiot-pneumothorax',
    storageBucket: 'qiot-pneumothorax.firebasestorage.app',
  );

}